version: "3.3"

services:
  chrome-magic:
    image: alpeware/chrome-headless-trunk
    ports:
      - 9222:9222
    networks:
      proxy_network:
  mssql:
    image: microsoft/mssql-server-linux
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=AAABBBccc123
    volumes:
      - .data:/var/opt/mssql
    networks:
      backend:
  api:
    depends_on:
      - mssql
      - chrome-magic
#    restart: always
    networks:
      backend:
      frontend:
    image: seecis/sauron
    labels:
      - traefik.backend=sauron-api
      - traefik.frontend.rule=Host:api.sauron.localhost
      - traefik.docker.network=frontend
      - traefik.port=9091
    environment:
      - HOME=/saur
    entrypoint: sauron serve api --config /saur/config.toml
    volumes:
      - ./config:/saur
    expose:
      - 9091
    ports:
      - 9091:9091
  proxy:
    image: seecis/sauron
    labels:
      - traefik.backend=sauron-proxy
      - traefik.frontend.rule=Host:proxy.sauron.localhost
      - traefik.docker.network=frontend
      - traefik.port=8092
    environment:
      - HOME=/saur
    entrypoint: sauron proxy --config /saur/config.toml
    networks:
      proxy_network:
      frontend:
    volumes:
      - ./config:/saur
    ports:
      - 8092:8092
    expose:
      - 8092
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      backend:
  worker:
    depends_on:
      - mssql
    image: seecis/sauron
    entrypoint: sauron worker --config /saur/config.toml
    volumes:
      - ./config:/saur
    networks:
      backend:
      proxy_network:
  web:
    depends_on:
      - api
      - proxy
    image: seecis/sauron-web
    networks:
      frontend:
    entrypoint: serve dist -l tcp://0.0.0.0:5000
    ports:
      - 5000:5000
    labels:
      - traefik.backend=sauron-web
      - traefik.frontend.rule=Host:sauron.localhost
      - traefik.docker.network=frontend
      - traefik.port=5000
    expose:
      - 5000
  task-manager:
    image: seecis/sauron
networks:
  proxy_network:
    external: false
  backend:
    external: false
  frontend:
    external: true


